/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycompany.sdclient2;

import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author thi_s
 */
public class Chat extends javax.swing.JFrame {

    Socket server;
    private String receptor;
    ObjectOutputStream saida;

    
    Chat(String receptor, Socket server) {
        super("Chat com " + receptor);
        this.server = server;
        this.receptor = receptor;
        initComponents();
        start();
    }

    
    public void start(){
        this.pack();
        this.setVisible(true);
    }
    
    public void append_message(String receive){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPReceptor = new javax.swing.JPanel();
        jSPMessages = new javax.swing.JScrollPane();
        jEPMessages = new javax.swing.JEditorPane();
        jPDonations = new javax.swing.JPanel();
        jBrs2 = new javax.swing.JButton();
        jBrs10 = new javax.swing.JButton();
        jBrs20 = new javax.swing.JButton();
        jBrs50 = new javax.swing.JButton();
        jBrs100 = new javax.swing.JButton();
        jBrs200 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTFMessage = new javax.swing.JTextField();
        jBSendMessage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPReceptor.setBorder(javax.swing.BorderFactory.createTitledBorder("Receptador"));

        jEPMessages.setEditable(false);
        jEPMessages.setContentType("text/html"); // NOI18N
        jSPMessages.setViewportView(jEPMessages);

        jPDonations.setBorder(javax.swing.BorderFactory.createTitledBorder("Doações"));

        jBrs2.setText("R$ 2,00");
        jBrs2.setMaximumSize(new java.awt.Dimension(83, 25));
        jBrs2.setMinimumSize(new java.awt.Dimension(83, 25));
        jBrs2.setPreferredSize(new java.awt.Dimension(83, 25));
        jBrs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrs2ActionPerformed(evt);
            }
        });
        jPDonations.add(jBrs2);

        jBrs10.setText("R$ 10,00");
        jBrs10.setMaximumSize(new java.awt.Dimension(83, 25));
        jBrs10.setMinimumSize(new java.awt.Dimension(83, 25));
        jBrs10.setPreferredSize(new java.awt.Dimension(83, 25));
        jPDonations.add(jBrs10);

        jBrs20.setText("R$ 20,00");
        jBrs20.setMaximumSize(new java.awt.Dimension(83, 25));
        jBrs20.setMinimumSize(new java.awt.Dimension(83, 25));
        jBrs20.setPreferredSize(new java.awt.Dimension(83, 25));
        jBrs20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrs20ActionPerformed(evt);
            }
        });
        jPDonations.add(jBrs20);

        jBrs50.setText("R$ 50,00");
        jBrs50.setPreferredSize(new java.awt.Dimension(83, 25));
        jPDonations.add(jBrs50);

        jBrs100.setText("R$ 100,00");
        jPDonations.add(jBrs100);

        jBrs200.setText("R$ 200,00");
        jPDonations.add(jBrs200);

        javax.swing.GroupLayout jPReceptorLayout = new javax.swing.GroupLayout(jPReceptor);
        jPReceptor.setLayout(jPReceptorLayout);
        jPReceptorLayout.setHorizontalGroup(
            jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReceptorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPDonations, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSPMessages))
                .addContainerGap())
        );
        jPReceptorLayout.setVerticalGroup(
            jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReceptorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPDonations, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite uma mensagem: "));

        jTFMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFMessageActionPerformed(evt);
            }
        });

        jBSendMessage.setText("Enviar");
        jBSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSendMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTFMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBSendMessage))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSendMessage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPReceptor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFMessageActionPerformed

    private void jBrs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrs2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBrs2ActionPerformed

    private void jBrs20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrs20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBrs20ActionPerformed

    private void jBSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSendMessageActionPerformed
        try {
            saida = new ObjectOutputStream(server.getOutputStream());
            saida.writeObject(jTFMessage.getText());
            
        } catch (IOException ex) {
            Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            saida = null;
        }
    }//GEN-LAST:event_jBSendMessageActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSendMessage;
    private javax.swing.JButton jBrs10;
    private javax.swing.JButton jBrs100;
    private javax.swing.JButton jBrs2;
    private javax.swing.JButton jBrs20;
    private javax.swing.JButton jBrs200;
    private javax.swing.JButton jBrs50;
    private javax.swing.JEditorPane jEPMessages;
    private javax.swing.JPanel jPDonations;
    private javax.swing.JPanel jPReceptor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jSPMessages;
    private javax.swing.JTextField jTFMessage;
    // End of variables declaration//GEN-END:variables
}
