/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycompany.sdclient2;

import java.io.ObjectOutputStream;
import java.net.Socket;
import utils.Utils;

/**
 *
 * @author thi_s
 */
public class Login extends javax.swing.JFrame {

Socket connection;
    ObjectOutputStream saida;

    public Login(Socket connection) { 
        this.connection = connection;
        initComponents();
        start();
    }

    private void start(){
        this.pack();
        this.setVisible(true); 
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTGiAm = new javax.swing.ButtonGroup();
        jPReceptor = new javax.swing.JPanel();
        jLLogin = new javax.swing.JLabel();
        jTFLogin = new javax.swing.JTextField();
        jLPassword = new javax.swing.JLabel();
        jPFPassword = new javax.swing.JPasswordField();
        jBLogin = new javax.swing.JButton();
        jBCreateReceptor = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRBDoador = new javax.swing.JRadioButton();
        jRBRecept = new javax.swing.JRadioButton();
        jRBAdmin = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPReceptor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLLogin.setText("Login:");

        jLPassword.setText("Password:");

        jBLogin.setText("Login");
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });

        jBCreateReceptor.setText("Ainda não tenho uma conta");
        jBCreateReceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreateReceptorActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("EU SOU"));

        BTGiAm.add(jRBDoador);
        jRBDoador.setText("Doador");
        jRBDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBDoadorActionPerformed(evt);
            }
        });

        BTGiAm.add(jRBRecept);
        jRBRecept.setText("Receptor");

        BTGiAm.add(jRBAdmin);
        jRBAdmin.setText("Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBRecept)
                    .addComponent(jRBAdmin)
                    .addComponent(jRBDoador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRBDoador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBRecept)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRBAdmin))
        );

        javax.swing.GroupLayout jPReceptorLayout = new javax.swing.GroupLayout(jPReceptor);
        jPReceptor.setLayout(jPReceptorLayout);
        jPReceptorLayout.setHorizontalGroup(
            jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReceptorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPReceptorLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLPassword)
                            .addComponent(jLLogin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPFPassword)
                            .addComponent(jTFLogin)))
                    .addComponent(jBLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCreateReceptor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPReceptorLayout.setVerticalGroup(
            jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReceptorLayout.createSequentialGroup()
                .addGroup(jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPReceptorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPReceptorLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLPassword)
                            .addComponent(jPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCreateReceptor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPReceptor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBDoadorActionPerformed

    private void jBCreateReceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreateReceptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCreateReceptorActionPerformed

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        if (jRBDoador.isSelected()){
            Utils.sendMessage(connection, "dinho" + ":" + connection.getRemoteSocketAddress());
            new ReceptorsList(connection).setVisible(true);//que quer abrir
        }else if( jRBRecept.isSelected()){
            new Chat(connection).setVisible(true);//que quer abrir
        }else if(jRBAdmin.isSelected()){
            new ReceptorsList(connection).setVisible(true);//que quer abrir
        }
        dispose();
    }//GEN-LAST:event_jBLoginActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BTGiAm;
    private javax.swing.JButton jBCreateReceptor;
    private javax.swing.JButton jBLogin;
    private javax.swing.JLabel jLLogin;
    private javax.swing.JLabel jLPassword;
    private javax.swing.JPasswordField jPFPassword;
    private javax.swing.JPanel jPReceptor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBAdmin;
    private javax.swing.JRadioButton jRBDoador;
    private javax.swing.JRadioButton jRBRecept;
    private javax.swing.JTextField jTFLogin;
    // End of variables declaration//GEN-END:variables
}
